[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
grid-core = { path = "../core" }
risc0-zkvm = { version = "0.19.1" }
env_logger = "0.10"
serde = "1.0"
rand = "0.8.5"
k256 = {  version = "0.13.2", features = ["serde"] }
rand_core = "0.6.4"